# Generated by Django 5.1.2 on 2024-10-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssubject',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='businesssubject',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='businesssubject',
            name='description',
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='category_name',
            field=models.CharField(default='Default Category', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='location',
            field=models.CharField(default='town', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='name',
            field=models.CharField(default='DefaultName', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='standarduser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='founders/')),
                ('business_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='accounts.businesssubject')),
            ],
        ),
    ]
