# Generated by Django 5.1.2 on 2024-11-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_standarduser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(default='surname', max_length=50),
        ),
    ]
