# Generated by Django 5.1.2 on 2024-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_name_client_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.AlterField(
            model_name='standarduser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
