# Generated by Django 5.1.2 on 2024-11-22 17:31

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_businesssubject_user_remove_client_user_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssubject',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='businesssubject',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='businesssubject',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='businesssubject',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='businesssubject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='businesssubject',
            name='website',
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='business_subject_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='business_pics/'),
        ),
        migrations.AddField(
            model_name='businesssubject',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='business_subject_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='businesssubject',
            name='business_name',
            field=models.CharField(default='poslovnisubjekatdefault', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesssubject',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
