# Generated by Django 5.1.2 on 2024-11-23 17:20

import django.db.models.deletion
import django.utils.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_businesssubject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubjectToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=django.utils.crypto.get_random_string, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('business_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='accounts.businesssubject')),
            ],
        ),
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=django.utils.crypto.get_random_string, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_auth_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
