# Generated by Django 5.1.2 on 2024-11-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_businesssubjecttoken_clienttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubjecttoken',
            name='business_subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bs_auth_token', to='accounts.businesssubject'),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_auth_token', to='accounts.client'),
        ),
    ]
