# Generated by Django 5.1.2 on 2024-12-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_businesssubjecttoken_business_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubject',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='./business_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='./profile_pics/'),
        ),
    ]
