# Generated by Django 5.1.2 on 2024-12-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_businesssubject_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubject',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='business_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client_profile_pics/'),
        ),
    ]
