# Generated by Django 5.1.2 on 2024-12-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_businesssubject_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubject',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
