# Generated by Django 5.1.2 on 2024-11-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('type_of_sport', models.CharField(max_length=255)),
                ('is_suspended', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
