# Generated by Django 5.1.2 on 2024-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
