# Generated by Django 5.1.3 on 2024-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_field_latitude_field_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
