# Generated by Django 5.1.3 on 2024-11-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_alter_field_latitude_alter_field_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='fields/images/'),
        ),
    ]
