# Generated by Django 5.1.3 on 2024-11-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0007_alter_field_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='./images/'),
        ),
    ]
