# Generated by Django 5.1.3 on 2024-11-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0008_alter_field_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='picture',
            new_name='image',
        ),
    ]
