# Generated by Django 5.1.2 on 2024-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
