# Generated by Django 5.1.3 on 2024-11-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_business_subject'),
        ('fields', '0004_alter_field_latitude_alter_field_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.field'),
        ),
    ]
