# Generated by Django 5.1.3 on 2024-11-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_advertisement_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.DateField(),
        ),
    ]
