# Generated by Django 5.1.2 on 2024-12-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_advertisement_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
