# Generated by Django 5.1.2 on 2024-12-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_alter_advertisement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
