# Generated by Django 5.1.2 on 2025-01-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_advertisement_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration_hours',
            field=models.IntegerField(default=0),
        ),
    ]
