# Generated by Django 5.1.3 on 2024-11-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True, null=True)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
