# Generated by Django 5.1.3 on 2024-11-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_name_client_surname'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivnost',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.client'),
        ),
    ]
