# Generated by Django 5.1.3 on 2024-11-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_aktivnost_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktivnost',
            name='datum_kreiranja',
        ),
        migrations.AddField(
            model_name='aktivnost',
            name='datum',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='aktivnost',
            name='vrijeme',
            field=models.TimeField(null=True),
        ),
    ]
