# Generated by Django 5.1.3 on 2024-11-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_aktivnost_datum_kreiranja_aktivnost_datum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivnost',
            name='teren',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
