# Generated by Django 5.1.3 on 2024-11-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_businesssubjecttoken_business_subject_and_more'),
        ('activities', '0003_remove_aktivnost_datum_kreiranja_aktivnost_datum_and_more'),
        ('fields', '0009_rename_picture_field_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('numberOfMembers', models.IntegerField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.client')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.field')),
            ],
        ),
        migrations.DeleteModel(
            name='Aktivnost',
        ),
    ]
