# Generated by Django 5.1.2 on 2024-12-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activities_delete_aktivnost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='numberOfMembers',
            new_name='NumberOfParticipants',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='name',
            new_name='titel',
        ),
    ]
