# Generated by Django 5.1.2 on 2024-12-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_rename_numberofmembers_activities_numberofparticipants_and_more'),
        ('fields', '0011_field_precise_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.sport'),
        ),
    ]
