# Generated by Django 5.1.3 on 2025-01-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activities_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
