# Generated by Django 5.1.3 on 2025-01-09 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activities_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
