# Generated by Django 5.1.3 on 2025-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_businesssubject_favorite_fields_and_more'),
        ('activities', '0008_activities_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='participants',
            field=models.ManyToManyField(related_name='activities_participated', to='accounts.client'),
        ),
    ]
