# Generated by Django 5.1.3 on 2025-01-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_businesssubject_favorite_fields_and_more'),
        ('activities', '0009_activities_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='participants',
            field=models.ManyToManyField(related_name='joined_activities', to='accounts.client'),
        ),
    ]
