# Generated by Django 5.1.3 on 2025-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_businesssubject_favorite_fields_and_more'),
        ('activities', '0010_alter_activities_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='participants',
            field=models.ManyToManyField(related_name='activities_participated', to='accounts.client'),
        ),
    ]
