# Generated by Django 5.1.2 on 2025-01-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_businesssubject_favorite_fields_and_more'),
        ('activities', '0012_alter_activities_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='duration_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.comment'),
        ),
    ]
