# Generated by Django 5.1.2 on 2024-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Review',
        ),
    ]
