# Generated by Django 5.1.3 on 2024-11-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_name_client_surname'),
        ('fields', '0002_alter_field_is_suspended'),
        ('reviews', '0002_rename_item_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
        migrations.AddField(
            model_name='review',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.field'),
        ),
    ]
